# This is a basic workflow to help you get started with Actions

name: My_First_workflow


on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [opened, synchronize]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
            java-version: '17'
            distribution: 'zulu'
            
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Show directory
        run: 'pwd'

      - name: List files
        run: 'ls -al'

      - name: Install dependecies
        run: 'mvn compile'

      - name: Build application
        run: 'mvn package -DskipTests'

      - name: Test Application
        run: 'mvn test'
